/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.BorderFactory;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.KeyStroke;
import utility.BDutility;

/**
 *
 * @author Sexon
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    
    
    public Dashboard() {
        initComponents();
        BDutility.setImage(this, "images/mainbackG.png", 1366, 768);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(2,2,2,2, Color.GRAY));
        
        setupShortcuts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnMarkAttendance = new javax.swing.JButton();
        btnRegisterUser = new javax.swing.JButton();
        btnGenerateQr = new javax.swing.JButton();
        btnViewAttendance = new javax.swing.JButton();
        btnViewUser = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnViewQr = new javax.swing.JButton();
        btnManual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("x");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 102, 0,30));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnMarkAttendance.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnMarkAttendance.setText("Mark Attendance");
        btnMarkAttendance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 3, true));
        btnMarkAttendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMarkAttendance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMarkAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkAttendanceActionPerformed(evt);
            }
        });

        btnRegisterUser.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnRegisterUser.setText("Register User");
        btnRegisterUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 3, true));
        btnRegisterUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegisterUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterUserActionPerformed(evt);
            }
        });

        btnGenerateQr.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnGenerateQr.setText("Generate Qr");
        btnGenerateQr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 3, true));
        btnGenerateQr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerateQr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenerateQr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateQrActionPerformed(evt);
            }
        });

        btnViewAttendance.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnViewAttendance.setText("View Attendance");
        btnViewAttendance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 3, true));
        btnViewAttendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewAttendance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAttendanceActionPerformed(evt);
            }
        });

        btnViewUser.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnViewUser.setText("View User");
        btnViewUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 3, true));
        btnViewUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUserActionPerformed(evt);
            }
        });

        btnUpdateUser.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnUpdateUser.setText("Update User");
        btnUpdateUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 3, true));
        btnUpdateUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        btnDeleteUser.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnDeleteUser.setText("Delete User");
        btnDeleteUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 3, true));
        btnDeleteUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        btnViewQr.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnViewQr.setText("View Qrs");
        btnViewQr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 3, true));
        btnViewQr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewQr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewQr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewQrActionPerformed(evt);
            }
        });

        btnManual.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnManual.setText("Manual");
        btnManual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 3, true));
        btnManual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMarkAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerateQr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdateUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewQr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegisterUser, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnManual, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnRegisterUser, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerateQr, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMarkAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateUser, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteUser, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewUser, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewQr, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManual, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1124, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    void resetButtonColors() { 
        btnMarkAttendance.setBackground(Color.WHITE); 
        btnRegisterUser.setBackground(Color.WHITE);
        btnGenerateQr.setBackground(Color.WHITE);
        btnViewAttendance.setBackground(Color.WHITE); 
        btnViewUser.setBackground(Color.WHITE); 
        btnUpdateUser.setBackground(Color.WHITE); 
        btnDeleteUser.setBackground(Color.WHITE);
        btnViewQr.setBackground(Color.WHITE); }
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnMarkAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkAttendanceActionPerformed
        resetButtonColors();
        btnMarkAttendance.setBackground(Color.GREEN);
        
        Mark_Attendance attFrame = new Mark_Attendance();
        attFrame.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override 
            public void windowClosed(java.awt.event.WindowEvent e) { 
                btnMarkAttendance.setBackground(Color.WHITE);
            } 
        });
        attFrame.setVisible(true);
    }//GEN-LAST:event_btnMarkAttendanceActionPerformed

    private void btnRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterUserActionPerformed
        resetButtonColors();
        btnRegisterUser.setBackground(Color.GREEN);
 
        UserRegistration regFrame = new UserRegistration();
        regFrame.addWindowListener(new java.awt.event.WindowAdapter() { 
            @Override 
            public void windowClosed(java.awt.event.WindowEvent e) { 
            btnRegisterUser.setBackground(Color.WHITE); 
        } 
        });
        regFrame.setVisible(true);
    }//GEN-LAST:event_btnRegisterUserActionPerformed

    private void btnGenerateQrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateQrActionPerformed
        resetButtonColors();
        btnGenerateQr.setBackground(Color.GREEN);
        
        GenerateQr qrFrame = new GenerateQr();
        qrFrame.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override 
        public void windowClosed(java.awt.event.WindowEvent e) {
            btnGenerateQr.setBackground(Color.WHITE);
        }
        });
        qrFrame.setVisible(true);
    }//GEN-LAST:event_btnGenerateQrActionPerformed

    private void btnViewAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAttendanceActionPerformed
        resetButtonColors();
        btnViewAttendance.setBackground(Color.GREEN);
        
        ViewAttendance viewAttFrame = new ViewAttendance();
        viewAttFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) { 
                btnViewAttendance.setBackground(Color.WHITE);
            }
        });
        viewAttFrame.setVisible(true);
    }//GEN-LAST:event_btnViewAttendanceActionPerformed

    
    
    private void btnViewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUserActionPerformed
        resetButtonColors();
        btnViewUser.setBackground(Color.GREEN);
        
        ViewUser viewUserFrame = new ViewUser();
        viewUserFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                btnViewUser.setBackground(Color.WHITE);
            }
        });
        viewUserFrame.setVisible(true);
    }//GEN-LAST:event_btnViewUserActionPerformed

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        resetButtonColors();
        btnUpdateUser.setBackground(Color.GREEN);
        new UpdateUser().setVisible(true);
        
        UpdateUser updateFrame = new UpdateUser();
        updateFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override 
            public void windowClosed(java.awt.event.WindowEvent e) {
                btnUpdateUser.setBackground(Color.WHITE);
            }
        });
        updateFrame.setVisible(true);
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        resetButtonColors();
        btnDeleteUser.setBackground(Color.GREEN);
        DeleteUser delFrame = new DeleteUser();
        delFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override 
            public void windowClosed(java.awt.event.WindowEvent e) { 
                btnDeleteUser.setBackground(Color.WHITE);
            } 
        });
        delFrame.setVisible(true);
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnViewQrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewQrActionPerformed
        resetButtonColors();
        btnViewQr.setBackground(Color.GREEN);
        
        ViewQrs viewQrFrame = new ViewQrs();
        viewQrFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) { 
                btnViewQr.setBackground(Color.WHITE); 
            }  
        });
        viewQrFrame.setVisible(true);
    }//GEN-LAST:event_btnViewQrActionPerformed

    
    
    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
        JTextArea manualArea = new JTextArea(); 
        manualArea.setText(
            "# SYSTEM WORKFLOW\n\n" +
            "1. Register User\n" +
            "   • Fill in required fields: LRN, Full Name, Gender, Section, Contact Number, Adviser, Workplace.\n" +
            "   • Upload a profile image.\n" +
            "   • Click Register to save the user profile.\n\n" +

            "2. Generate QR Code\n" +
            "   • Go to the Generate QR module.\n" +
            "   • Select the user, review information, and click Generate QR.\n" +
            "   • Save the QR code securely.\n\n" +

            "3. Mark Attendance\n" +
            "   • Go to Mark Attendance.\n" +
            "   • Scan or input the QR code.\n" +
            "   • The system logs attendance automatically based on day rules.\n\n" +

            "# ATTENDANCE RULES\n" +
            "   • Monday–Thursday: Work hours 1:00 PM – 7:00 PM, grace period until 2:00 PM.\n" +
            "   • Friday: Work hours 6:00 AM – 7:00 PM, grace period until 9:00 AM.\n" +
            "   • Saturday–Sunday: Attendance is not allowed.\n\n" +

            "### MAIN MENU FUNCTIONS ###\n" +
            "   • Register User – Add and save user profile.\n" +
            "   • Generate QR – Create QR codes.\n" +
            "   • Mark Attendance – Scan QR to log attendance.\n" +
            "   • View Attendance – Filter and export logs.\n" +
            "   • View QRs – Preview generated QR codes.\n" +
            "   • View User – See registered users.\n" +
            "   • Update User – Modify user details.\n" +
            "   • Delete User – Permanently remove a user.\n\n" +

            "# DO’S:\n" +
            "   • Double-check user info before generating QR codes.\n" +
            "   • Use Update User to correct mistakes.\n" +
            "   • Mark attendance daily and verify logs.\n" +
            "   • Save QR codes securely.\n" +
            "   • Use View Attendance to monitor attendance patterns.\n\n" +

            "# DON’TS:\n" +
            "   • Don’t falsify attendance records.\n" +
            "   • Don’t delete users without confirming.\n" +
            "   • Don’t generate QR codes with incomplete info.\n" +
            "   • Don’t mark attendance manually unless necessary.\n" +
            "   • Don’t share QR codes publicly.\n" +
            "   • Don’t skip updating user details when changes occur.\n"
        ); 

        manualArea.setEditable(false); 
        manualArea.setLineWrap(true); 
        manualArea.setWrapStyleWord(true); 
        manualArea.setFont(new Font("Segoe UI", Font.PLAIN, 14)); 

        JScrollPane scrollPane = new JScrollPane(manualArea); 
        scrollPane.setPreferredSize(new Dimension(700, 400)); 

        JOptionPane.showMessageDialog(this, scrollPane, "📘 Help Manual", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnManualActionPerformed
    
    private void setupShortcuts() { 
        InputMap inputMap = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW); 
        ActionMap actionMap = this.getRootPane().getActionMap(); 
        
        inputMap.put(KeyStroke.getKeyStroke("F3"), "markAttendance"); 
        actionMap.put("markAttendance", new AbstractAction() { 
            @Override
            public void actionPerformed(ActionEvent e) { btnMarkAttendance.doClick(); } 
        });
        
        inputMap.put(KeyStroke.getKeyStroke("F4"), "viewAttendance"); 
        actionMap.put("viewAttendance", new AbstractAction() { 
            @Override
            public void actionPerformed(ActionEvent e) { btnViewAttendance.doClick(); } 
        }); 
        
        inputMap.put(KeyStroke.getKeyStroke("F2"), "generateQR"); 
        actionMap.put("generateQR", new AbstractAction() { 
            @Override
            public void actionPerformed(ActionEvent e) { btnGenerateQr.doClick(); } 
        }); 
        
        inputMap.put(KeyStroke.getKeyStroke("F1"), "Register_User"); 
        actionMap.put("Register_User", new AbstractAction() { 
            @Override
            public void actionPerformed(ActionEvent e) { btnRegisterUser.doClick(); } 
        }); 
        
        inputMap.put(KeyStroke.getKeyStroke("ESCAPE"), "closeWindow"); 
        actionMap.put("closeWindow", new AbstractAction() { 
            @Override
            public void actionPerformed(ActionEvent e) { dispose(); } 
        }); 
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnGenerateQr;
    private javax.swing.JButton btnManual;
    private javax.swing.JButton btnMarkAttendance;
    private javax.swing.JButton btnRegisterUser;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JButton btnViewAttendance;
    private javax.swing.JButton btnViewQr;
    private javax.swing.JButton btnViewUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
