/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import dao.ConnectionProvider;
import java.sql.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.sql.PreparedStatement;
import java.time.DayOfWeek;
import java.time.LocalTime;
import utility.BDutility;
/**
 *
 * @author Sexon
 */
public class Mark_Attendance extends javax.swing.JFrame implements Runnable, ThreadFactory {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mark_Attendance.class.getName());
    
     private WebcamPanel panel = null;
    private Webcam webcam = null;
    private ExecutorService executor = Executors.newSingleThreadExecutor(this);
    private volatile boolean running =  true;
    /**
     * Creates new form Mark_Attendance
     */
    /*private void testWebcam() {
    System.out.println("Available webcams: " + Webcam.getWebcams().size());
    Webcam defaultWebcam = Webcam.getDefault();
        if (defaultWebcam != null) {
            System.out.println("Default webcam: " + defaultWebcam.getName());
            System.out.println("Webcam open: " + defaultWebcam.isOpen());
        } else {
            System.out.println("No webcam found!");
        }
    }*/
    
    public Mark_Attendance() {
        initComponents();
        //testWebcam();
        initWebcam();
        BDutility.setImage(this, "images/registrationBG.png",1200, 650);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(2,2,2,2, Color.GRAY));
        
        
        Timer timer = new Timer(1,e->updateTime());
        timer.start();
        
    }
    
    private void updateTime(){
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd    HH:mm:ss.SSS");
        lblTime.setText(simpleDateFormat.format(new Date()));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        webCamPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblTimeInTimeOut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 615));
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mark Attendance");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("x");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        webCamPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DATE:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIME:");

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("TIME");

        lblName.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));

        lblTimeInTimeOut.setBackground(new java.awt.Color(255, 0, 0));
        lblTimeInTimeOut.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        lblTimeInTimeOut.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(webCamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(71, 71, 71)
                                .addComponent(jLabel4))
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTimeInTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(webCamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(lblTimeInTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        running = false;
        stopWebcam();

        if(executor != null && !executor.isShutdown()){
            executor.shutdown();
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mark_Attendance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimeInTimeOut;
    private javax.swing.JPanel webCamPanel;
    // End of variables declaration//GEN-END:variables
    
     Map<String,String> resultMap = new HashMap<>();
    
    @Override
    public void run() {
      do{
          try{
              Thread.sleep(1000);
          }catch(InterruptedException ex){
          }
          
          try{
              Result result = null;
              BufferedImage image = null;
              if(webcam.isOpen()){
                  if((image= webcam.getImage())== null){
                      continue;
                  }
              }
              
              LuminanceSource source = new BufferedImageLuminanceSource(image);
              BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
              
              try{
                  result = new MultiFormatReader().decode(bitmap);
              }catch(NotFoundException ex){
                  
              }
              
              if(result!=null){
                  String jsonString = result.getText();
                  Gson gson = new Gson();
                  java.lang.reflect.Type type = new TypeToken<Map<String,String>>(){    
                  }.getType();
                  resultMap = gson.fromJson(jsonString, type);
                  
                  String finalPath = BDutility.getPath("image\\ " + resultMap.get("Name")+".jpg");
                  CircularImageFrame(finalPath);
                  

              }
              
          }catch(Exception ex){
              ex.printStackTrace();
          }
          
      }while(running);
        
      
    }

    

    private void initWebcam() {
       webcam = Webcam.getDefault();
       if (webcam !=null){
           Dimension[] resolutions = webcam.getViewSizes();
           Dimension maxResolution =resolutions[resolutions.length-1];
           
           if(webcam.isOpen()){
               webcam.close();
               
           }
           
           webcam.setViewSize(maxResolution);
           webcam.open();
           
           panel = new WebcamPanel(webcam);
           panel.setPreferredSize(maxResolution);
           panel.setFPSDisplayed(true);
           
           webCamPanel.add(panel,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 510));
           executor.execute((Runnable) this);
           executor.shutdown();
             
       }else{
           System.out.println("ISSUE WITH WEBCAM");
       }
        
    }
    @Override
    public Thread newThread(Runnable r) {
       Thread t = new Thread(r, "My Thread");
       t.setDaemon(true);
       return t;
    }
    private void stopWebcam(){
        if(webcam!=null && webcam.isOpen()){
            webcam.close();
        }
    }
    private BufferedImage imagee = null;
    private void CircularImageFrame(String imagePath) {
       try{
           Connection con = ConnectionProvider.getCon();
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("SELECT * FROM immstudentdetails WHERE Name='" + resultMap.get("Name") + "'");
           if(!rs.next()){
               showPopUpForCertainDuration("USER IS NOT REGISTRED OR GOT DELETED","Invalid Qr",JOptionPane.ERROR_MESSAGE);
               return;
           }
           imagee = null;
           File imageFile = new File(imagePath);
           if(imageFile.exists()){
               try{
                   
                   imagee = ImageIO.read(new File(imagePath));
                   imagee = createCircularImage(imagee);
                   ImageIcon icon = new ImageIcon(imagee);
                   lblImage.setIcon(icon);
                   
                   
               }catch(Exception ex){
                   ex.printStackTrace();
               }
           }else{
               BufferedImage imageee = new BufferedImage(300,300,BufferedImage.TYPE_INT_ARGB);
               Graphics2D g2d = imageee.createGraphics();
               
               g2d.setColor(Color.BLACK);
               g2d.fillOval(10, 25, 250, 250);
               
               g2d.setFont(new Font("Serif",Font.BOLD,230));
               g2d.setColor(Color.RED);
               g2d.drawString(String.valueOf(resultMap.get("Name").charAt(0)).toUpperCase(), 50, 220);
               g2d.dispose();
               
               ImageIcon imageIconn = new ImageIcon(imageee);
               lblImage.setIcon(imageIconn);
               this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
               this.pack();
               this.setLocationRelativeTo(null);
               this.setVisible(true);
 
           }
           lblName.setHorizontalAlignment(JLabel.LEFT);
           lblName.setText(resultMap.get("Name"));
           if(!checkInCheckOut()){
           }
           
       }catch(Exception ex){
           ex.printStackTrace();
       }
    }

    private void showPopUpForCertainDuration(String popUpMessage, String popUpHeader, Integer iconId) throws HeadlessException {
     final JOptionPane optionPane = new JOptionPane(popUpMessage,iconId);
     final JDialog dialog = optionPane.createDialog(popUpHeader);
     Timer timer = new Timer(5000, (ActionEvent e) -> {
         dialog.dispose();
         clearUserDetails();
     });
     timer.setRepeats(false);
     timer.start();
     dialog.setVisible(true);
     
    }
    private void clearUserDetails() {
        lblTimeInTimeOut.setText("");
        lblTimeInTimeOut.setBackground(null);
        lblTimeInTimeOut.setForeground(null);
        lblTimeInTimeOut.setOpaque(false);
        lblName.setText("");
        lblImage.setIcon(null);
    }


    private BufferedImage createCircularImage(BufferedImage imagee) {
       int diameter = 285;
       BufferedImage resizedImage = new BufferedImage(diameter,diameter,BufferedImage.TYPE_INT_ARGB);
       Graphics2D g2 = resizedImage.createGraphics();
       g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_BILINEAR);
       g2.drawImage(imagee, 0,0,diameter,diameter,null);
       g2.dispose();
       
       BufferedImage circularImage= new BufferedImage(diameter,diameter, BufferedImage.TYPE_INT_ARGB);
       g2 =circularImage.createGraphics();
       Ellipse2D.Double circle = new Ellipse2D.Double(0,0,diameter,diameter);
       g2.setClip(circle);
       g2.drawImage(resizedImage,0,0,null);
       g2.dispose();
       return circularImage;
    }

    private boolean checkInCheckOut() throws HeadlessException, SQLException {
    String popUpHeader = null;
    String popUpMessage= null;
    Color color = null;
    
    Connection con = ConnectionProvider.getCon();
    
    LocalDate currentDate = LocalDate.now();
    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    
    LocalDateTime currentDateTime = LocalDateTime.now();
    DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    
    DayOfWeek currentDay = currentDate.getDayOfWeek();
    LocalTime workStartTime;
    LocalTime workEndTime;
    LocalTime timeInGraceStart;
    LocalTime timeInGraceEnd;

    switch (currentDay) {
        case MONDAY, TUESDAY, WEDNESDAY, THURSDAY -> {
            workStartTime = LocalTime.of(8, 0);      
            workEndTime = LocalTime.of(13, 0);       
            timeInGraceStart = LocalTime.of(8, 0);   
            timeInGraceEnd = LocalTime.of(9, 0);     
        }
        case FRIDAY -> {
            workStartTime = LocalTime.of(8, 0);      
            workEndTime = LocalTime.of(18, 0);       
            timeInGraceStart = LocalTime.of(8, 0);   
            timeInGraceEnd = LocalTime.of(9, 0);     
        }
        case SATURDAY, SUNDAY -> {
            popUpMessage = "Attendance is not allowed on weekends.\nPlease try again on a weekday.";
            popUpHeader = "Weekend - No Work";
            showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.WARNING_MESSAGE);
            return false;
        }
        default -> {
            workStartTime = LocalTime.of(8, 0);
            workEndTime = LocalTime.of(13, 0);
            timeInGraceStart = LocalTime.of(8, 0);
            timeInGraceEnd = LocalTime.of(9, 0);
        }
    }

    LocalTime currentTime = currentDateTime.toLocalTime();
    
    // FIX: Use PreparedStatement and column names instead of indices
    String query = "SELECT * FROM ImmStudentattendance WHERE Date=? AND LRN=?";
    PreparedStatement pst = con.prepareStatement(query);
    pst.setString(1, currentDate.format(dateFormatter));
    pst.setLong(2, Long.parseLong(resultMap.get("LRN")));
    ResultSet rs = pst.executeQuery();
    
    Connection connection = ConnectionProvider.getCon();
    if(rs.next()){
        // FIX: Use column name instead of index
        String checkOutDateTime = rs.getString("TimeOut");
        if(checkOutDateTime != null && !checkOutDateTime.trim().isEmpty()){
            popUpMessage = "Already TimeOut for the Day";
            popUpHeader = "Invalid TimeOut";
            showPopUpForCertainDuration(popUpMessage,popUpHeader,JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if (currentTime.isAfter(workEndTime)) {
            String endTimeFormatted = workEndTime.format(DateTimeFormatter.ofPattern("h a"));
            String currentTimeFormatted = currentTime.format(DateTimeFormatter.ofPattern("h:mm a"));
            String dayName = currentDay.toString().charAt(0) + currentDay.toString().substring(1).toLowerCase();
            
            popUpMessage = String.format("Time Out period has ended at %s on %s\nCurrent time: %s", 
                                        endTimeFormatted, dayName, currentTimeFormatted);
            popUpHeader = "Time Out Period Ended";
            showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.WARNING_MESSAGE);
            return false;  
        }
        
        // FIX: Use column name instead of index
        String checkInDateTime = rs.getString("TimeIn");
        LocalDateTime checkInLocalDateTime = LocalDateTime.parse(checkInDateTime,dateTimeFormatter);
        Duration duration = Duration.between(checkInLocalDateTime,currentDateTime);

        long hours = duration.toHours();
        long minutes = duration.minusHours(hours).toMinutes();
        long seconds = duration.minusHours(hours).minusMinutes(minutes).getSeconds();

        if(!(hours >0 || (hours == 0 && minutes >= 10 ))){
            long remainingMinutes = 15-minutes;
            long remainingSeconds = 60-seconds;

            popUpMessage = String.format("Your work duration is less than 15 minutes \nYou can check out after: %d minutes and %d seconds", remainingMinutes,remainingSeconds);
            popUpHeader = "Duration Warning";

            showPopUpForCertainDuration(popUpMessage,popUpHeader,JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        String updateQuery = "UPDATE ImmStudentattendance set TimeOut=?,workduration=? WHERE Date=? and LRN=?";
        PreparedStatement preparedStatement = connection.prepareStatement(updateQuery);
        preparedStatement.setString(1, currentDateTime.format(dateTimeFormatter));
        preparedStatement.setString(2, ""+ hours + "Hours and " + minutes + "Minutes");
        preparedStatement.setString(3, currentDate.format(dateFormatter));
        preparedStatement.setLong(4, Long.parseLong(resultMap.get("LRN")));
        
        preparedStatement.executeUpdate();
        popUpHeader = "TimeOut";
        popUpMessage = "Time out at " + currentDateTime.format(dateTimeFormatter)+ "\nWork Duration " + hours +"Hours and " + minutes + "Minutes";
        
        color = Color.RED;
    
    } else {
        
        if (currentTime.isBefore(workStartTime) || currentTime.isAfter(workEndTime)) {
            String startTimeFormatted = workStartTime.format(DateTimeFormatter.ofPattern("h a"));
            String endTimeFormatted = workEndTime.format(DateTimeFormatter.ofPattern("h a"));
            String currentTimeFormatted = currentTime.format(DateTimeFormatter.ofPattern("h:mm a"));
            String dayName = currentDay.toString().charAt(0) + currentDay.toString().substring(1).toLowerCase();

            if (currentDay == DayOfWeek.FRIDAY) {
                popUpMessage = String.format("On %s, attendance can only be marked between %s and %s\nCurrent time: %s", 
                                            dayName, startTimeFormatted, endTimeFormatted, currentTimeFormatted);
            } else {
                popUpMessage = String.format("On %s, attendance can only be marked between %s and %s (morning shift only)\nCurrent time: %s", 
                                            dayName, startTimeFormatted, endTimeFormatted, currentTimeFormatted);
            }

            popUpHeader = "Outside Work Hours";
            showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        String insertQuery = "INSERT INTO ImmStudentattendance (LRN,Name,Gender,Section,Date,TimeIn) VALUES(?,?,?,?,?,?)";
        PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
        preparedStatement.setLong(1, Long.parseLong(resultMap.get("LRN")));
        preparedStatement.setString(2, resultMap.get("Name"));
        preparedStatement.setString(3, resultMap.get("Gender"));
        preparedStatement.setString(4, resultMap.get("Section"));
        preparedStatement.setString(5, currentDate.format(dateFormatter));
        preparedStatement.setString(6, currentDateTime.format(dateTimeFormatter));
        preparedStatement.executeUpdate();
        popUpHeader="TimeIn";
        popUpMessage = "Time in at " + currentDateTime.format(dateTimeFormatter);
        color = Color.GREEN;
    }
    
    lblTimeInTimeOut.setHorizontalAlignment(JLabel.CENTER);
    lblTimeInTimeOut.setText(popUpHeader);
    lblTimeInTimeOut.setForeground(color);
    lblTimeInTimeOut.setBackground(Color.darkGray);
    lblTimeInTimeOut.setOpaque(true);
    showPopUpForCertainDuration(popUpMessage,popUpHeader, JOptionPane.INFORMATION_MESSAGE);
    return true;
}
    @Override
    public void paint(Graphics g){
        super.paint(g);
        if(imagee!=null){
            g.drawImage(imagee,0,0,null);
        }
    }
    
    

}
