/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import dao.ConnectionProvider;

import jakarta.mail.*; 
import jakarta.mail.internet.*; 
import jakarta.activation.*;
import java.sql.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.PasswordAuthentication;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.time.DayOfWeek;
import java.time.LocalTime;
import utility.BDutility;
import java.sql.PreparedStatement;
import java.util.Properties;


/**
 *
 * @author Sexon
 */
public class Mark_Attendance extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mark_Attendance.class.getName());
    
    private Map<String,String> resultMap = new HashMap<>();
    private BufferedImage imagee = null;

    /**
     * Creates new form Mark_Attendance
     */
    
    private static final String ADMIN_EMAIL = "kerbysexon0827@gmail.com";
    private static final String JAVA_TEACHER_EMAIL = "sexon.kerby.linquico@gmail.com";
    private static final String ORACLE_TEACHER_EMAIL = "kerbszxc@gmail.com";
    
    private static final Map<String, String> SECTION_TEACHER_MAP = new HashMap<String, String>() {{
        put("Java", JAVA_TEACHER_EMAIL);
        put("Oracle", ORACLE_TEACHER_EMAIL);
    }};
    
    public Mark_Attendance() {
        initComponents();
        BDutility.setImage(this, "images/registrationBG.png", 930, 480);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.GRAY));
        
        // Setup scanner input field
        setupScannerInput();
        
        Timer timer = new Timer(1, e -> updateTime());
        timer.start();
    }
    
    private void setupScannerInput() {
        // Add key listener to the text field for scanner input
        txtScannerInput.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    processScannedData();
                }
            }
        });
        
        // Request focus on the text field when form loads
        txtScannerInput.requestFocus();
        
        // Add focus listener to ensure field stays focused
        this.addWindowFocusListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowGainedFocus(java.awt.event.WindowEvent e) {
                txtScannerInput.requestFocusInWindow();
            }
        });
    }
    
    private void processScannedData() {
        String scannedText = txtScannerInput.getText().trim();
        
        if (scannedText.isEmpty()) {
            return;
        }
        
        try {
            // Parse JSON from QR code
            Gson gson = new Gson();
            java.lang.reflect.Type type = new TypeToken<Map<String,String>>(){}.getType();
            resultMap = gson.fromJson(scannedText, type);
            
            // Display user information
            String finalPath = BDutility.getPath("image\\" + resultMap.get("Name") + ".jpg");
            displayUserInfo(finalPath);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, 
                "Invalid QR Code format", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            
            txtScannerInput.setText("");
        } finally {
            // Clear the text field for next scan
            txtScannerInput.setText("");
        }
    }
    
    private void updateTime() {
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd    HH:mm:ss.SSS");
        lblTime.setText(simpleDateFormat.format(new Date()));
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExistRegis = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblTimeInTimeOut = new javax.swing.JLabel();
        txtScannerInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MARK ATTENDANCE");

        btnExistRegis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExistRegis.setText("X");
        btnExistRegis.setBorder(null);
        btnExistRegis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExistRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExistRegisActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DAte & time:");

        jLabel5.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Scan qr code here:");

        lblTime.setBackground(new java.awt.Color(255, 255, 255));
        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblName.setBackground(new java.awt.Color(70, 73, 75));
        lblName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 255, 0));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setToolTipText("");
        lblName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblName.setName(""); // NOI18N
        lblName.setOpaque(true);

        lblTimeInTimeOut.setBackground(new java.awt.Color(70, 73, 75));
        lblTimeInTimeOut.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblTimeInTimeOut.setForeground(new java.awt.Color(0, 255, 0));
        lblTimeInTimeOut.setToolTipText("");
        lblTimeInTimeOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTimeInTimeOut.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtScannerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExistRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTimeInTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExistRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtScannerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTimeInTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExistRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExistRegisActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExistRegisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mark_Attendance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExistRegis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimeInTimeOut;
    private javax.swing.JTextField txtScannerInput;
    // End of variables declaration//GEN-END:variables
    
    private void displayUserInfo(String imagePath) {
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM immstudentdetails WHERE Name='" + resultMap.get("Name") + "'");
            
            if (!rs.next()) {
                showPopUpForCertainDuration("USER IS NOT REGISTERED OR GOT DELETED", "Invalid QR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            imagee = null;
            File imageFile = new File(imagePath);
            
            if (imageFile.exists()) {
                try {
                    imagee = ImageIO.read(new File(imagePath));
                    imagee = createCircularImage(imagee);
                    ImageIcon icon = new ImageIcon(imagee);
                    lblImage.setIcon(icon);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            } else {
                BufferedImage imageee = new BufferedImage(300, 300, BufferedImage.TYPE_INT_ARGB);
                Graphics2D g2d = imageee.createGraphics();
                
                g2d.setColor(Color.BLACK);
                g2d.fillOval(10, 25, 250, 250);
                
                g2d.setFont(new Font("Serif", Font.BOLD, 230));
                g2d.setColor(Color.RED);
                g2d.drawString(String.valueOf(resultMap.get("Name").charAt(0)).toUpperCase(), 50, 220);
                g2d.dispose();
                
                ImageIcon imageIconn = new ImageIcon(imageee);
                lblImage.setIcon(imageIconn);
            }
            
            lblName.setHorizontalAlignment(JLabel.LEFT);
            lblName.setText(resultMap.get("Name"));
            checkInCheckOut();
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void showPopUpForCertainDuration(String popUpMessage, String popUpHeader, Integer iconId) throws HeadlessException {
        final JOptionPane optionPane = new JOptionPane(popUpMessage, iconId);
        final JDialog dialog = optionPane.createDialog(popUpHeader);
        Timer timer = new Timer(5000, (ActionEvent e) -> {
            dialog.dispose();
            clearUserDetails();
        });
        timer.setRepeats(false);
        timer.start();
        dialog.setVisible(true);
    }
    
    private void clearUserDetails() {
        lblTimeInTimeOut.setText("");
        lblTimeInTimeOut.setBackground(null);
        lblTimeInTimeOut.setForeground(null);
        lblTimeInTimeOut.setOpaque(false);
        lblName.setText("");
        lblImage.setIcon(null);
    }
    
    private String[] getEmailRecipients(String section) {
        String teacherEmail = null;
        
        // Case-insensitive search for teacher email
        if (section != null) {
            for (Map.Entry<String, String> entry : SECTION_TEACHER_MAP.entrySet()) {
                if (entry.getKey().equalsIgnoreCase(section)) {
                    teacherEmail = entry.getValue();
                    break;
                }
            }
        }
        
        if (teacherEmail != null && !teacherEmail.trim().isEmpty()) {
            // Send to both teacher and admin
            return new String[]{teacherEmail, ADMIN_EMAIL};
        } else {
            // If no teacher mapping found, send only to admin
            System.out.println("Warning: No teacher email configured for section: " + section);
            return new String[]{ADMIN_EMAIL};
        }
    }
    
    /**
     * Send email to multiple recipients
     */
    private void sendEmail(String[] recipients, String subject, String body) {
        final String username = "linxonkerby@gmail.com"; 
        final String password = "pwopjmtyyferbpcb";    

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        Session session = Session.getInstance(props,
        new jakarta.mail.Authenticator() {
            protected jakarta.mail.PasswordAuthentication getPasswordAuthentication() {
                return new jakarta.mail.PasswordAuthentication(username, password);
            }
        });

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(username));
            
            // Create array of InternetAddress for multiple recipients
            InternetAddress[] addressTo = new InternetAddress[recipients.length];
            for (int i = 0; i < recipients.length; i++) {
                addressTo[i] = new InternetAddress(recipients[i]);
            }
            message.setRecipients(Message.RecipientType.TO, addressTo);
            
            message.setSubject(subject);
            message.setText(body);

            Transport.send(message);
            System.out.println("Email sent successfully to " + recipients.length + " recipients!");

        } catch (MessagingException e) {
            e.printStackTrace();
            System.err.println("Failed to send email notification");
        }
    }

    
    

    private BufferedImage createCircularImage(BufferedImage imagee) {
        int diameter = 285;
        BufferedImage resizedImage = new BufferedImage(diameter, diameter, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = resizedImage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(imagee, 0, 0, diameter, diameter, null);
        g2.dispose();
        
        BufferedImage circularImage = new BufferedImage(diameter, diameter, BufferedImage.TYPE_INT_ARGB);
        g2 = circularImage.createGraphics();
        Ellipse2D.Double circle = new Ellipse2D.Double(0, 0, diameter, diameter);
        g2.setClip(circle);
        g2.drawImage(resizedImage, 0, 0, null);
        g2.dispose();
        return circularImage;
    }
    
    private boolean checkInCheckOut() throws HeadlessException, SQLException {
        String popUpHeader = null;
        String popUpMessage = null;
        Color color = null;
        
        Connection con = ConnectionProvider.getCon();
        
        LocalDate currentDate = LocalDate.now();
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        
        LocalDateTime currentDateTime = LocalDateTime.now();
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        
        DayOfWeek currentDay = currentDate.getDayOfWeek();
        LocalTime workStartTime;
        LocalTime workEndTime;
        LocalTime timeInGraceStart;
        LocalTime timeInGraceEnd;

        switch (currentDay) {
            case MONDAY, TUESDAY, WEDNESDAY, THURSDAY -> {
                workStartTime = LocalTime.of(6, 0);
                workEndTime = LocalTime.of(13, 0);
                timeInGraceStart = LocalTime.of(6, 0);
                timeInGraceEnd = LocalTime.of(9, 0);
            }
            case FRIDAY, SUNDAY -> {
                workStartTime = LocalTime.of(6, 0);
                workEndTime = LocalTime.of(19, 0);
                timeInGraceStart = LocalTime.of(6, 0);
                timeInGraceEnd = LocalTime.of(9, 0);
            }
            /*case SATURDAY, SUNDAY -> {
                popUpMessage = "Attendance is not allowed on weekends.\nPlease try again on a weekday.";
                popUpHeader = "Weekend - No Work";
                showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.WARNING_MESSAGE);
                return false;
            }*/
            default -> {
                workStartTime = LocalTime.of(6, 0);
                workEndTime = LocalTime.of(13, 0);
                timeInGraceStart = LocalTime.of(6, 0);
                timeInGraceEnd = LocalTime.of(9, 0);
            }
        }

        LocalTime currentTime = currentDateTime.toLocalTime();
        
        String query = "SELECT * FROM ImmStudentattendance WHERE Date=? AND LRN=?";
        PreparedStatement pst = (PreparedStatement) con.prepareStatement(query);
        pst.setString(1, currentDate.format(dateFormatter));
        pst.setLong(2, Long.parseLong(resultMap.get("LRN")));
        ResultSet rs = pst.executeQuery();
        
        Connection connection = ConnectionProvider.getCon();
        if (rs.next()) {
            String checkOutDateTime = rs.getString("TimeOut");
            if (checkOutDateTime != null && !checkOutDateTime.trim().isEmpty()) {
                popUpMessage = "Already TimeOut for the Day";
                popUpHeader = "Invalid TimeOut";
                showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.ERROR_MESSAGE);
                return false;
            }
            
            if (currentTime.isAfter(workEndTime)) {
                String endTimeFormatted = workEndTime.format(DateTimeFormatter.ofPattern("h a"));
                String currentTimeFormatted = currentTime.format(DateTimeFormatter.ofPattern("h:mm a"));
                String dayName = currentDay.toString().charAt(0) + currentDay.toString().substring(1).toLowerCase();
                
                popUpMessage = String.format("Time Out period has ended at %s on %s\nCurrent time: %s",
                        endTimeFormatted, dayName, currentTimeFormatted);
                popUpHeader = "Time Out Period Ended";
                showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.WARNING_MESSAGE);
                return false;
            }
            
            String checkInDateTime = rs.getString("TimeIn");
            LocalDateTime checkInLocalDateTime = LocalDateTime.parse(checkInDateTime, dateTimeFormatter);
            Duration duration = Duration.between(checkInLocalDateTime, currentDateTime);

            long hours = duration.toHours();
            long minutes = duration.minusHours(hours).toMinutes();
            long seconds = duration.minusHours(hours).minusMinutes(minutes).getSeconds();

            if (!(hours > 0 || (hours == 0 && minutes >= 30))) {
                long remainingMinutes = 30 - minutes;
                long remainingSeconds = 60 - seconds;

                popUpMessage = String.format("Your work duration is less than 30 minutes \nYou can check out after: %d minutes and %d seconds", remainingMinutes, remainingSeconds);
                popUpHeader = "Duration Warning";

                showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.WARNING_MESSAGE);
                return false;
            }
            
            String updateQuery = "UPDATE ImmStudentattendance set TimeOut=?,workduration=? WHERE Date=? and LRN=?";
            PreparedStatement preparedStatement = connection.prepareStatement(updateQuery);
            preparedStatement.setString(1, currentDateTime.format(dateTimeFormatter));
            preparedStatement.setString(2, ""+ hours + "Hours and " + minutes + "Minutes");
            preparedStatement.setString(3, currentDate.format(dateFormatter));
            preparedStatement.setLong(4, Long.parseLong(resultMap.get("LRN")));
            
            preparedStatement.executeUpdate();
            popUpHeader = "TimeOut";
            popUpMessage = "Time out at " + currentDateTime.format(dateTimeFormatter) + "\nWork Duration " + hours + "Hours and " + minutes + "Minutes";
     
            color = Color.RED;
            
            try {
                String[] recipients = getEmailRecipients(resultMap.get("Section"));
                sendEmail(recipients, "Time Out Confirmation",
                        "Student: " + resultMap.get("Name") + 
                        "\nSection: " + resultMap.get("Section") +
                        "\nLRN: " + resultMap.get("LRN") +
                        "\nClocked out at: " + currentDateTime.format(dateTimeFormatter) +
                        "\nWork Duration: " + hours + " Hours and " + minutes + " Minutes");
            } catch (Exception e) {
                System.err.println("Email notification failed, but attendance recorded successfully");
            }  
            
        } else {
            if (currentTime.isBefore(workStartTime) || currentTime.isAfter(workEndTime)) {
                String startTimeFormatted = workStartTime.format(DateTimeFormatter.ofPattern("h a"));
                String endTimeFormatted = workEndTime.format(DateTimeFormatter.ofPattern("h a"));
                String currentTimeFormatted = currentTime.format(DateTimeFormatter.ofPattern("h:mm a"));
                String dayName = currentDay.toString().charAt(0) + currentDay.toString().substring(1).toLowerCase();

                if (currentDay == DayOfWeek.FRIDAY) {
                    popUpMessage = String.format("On %s, attendance can only be marked between %s and %s\nCurrent time: %s",
                            dayName, startTimeFormatted, endTimeFormatted, currentTimeFormatted);
                } else {
                    popUpMessage = String.format("On %s, attendance can only be marked between %s and %s (morning shift only)\nCurrent time: %s",
                            dayName, startTimeFormatted, endTimeFormatted, currentTimeFormatted);
                }

                popUpHeader = "Outside Work Hours";
                showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.WARNING_MESSAGE);
                return false;
            }
            
            String insertQuery = "INSERT INTO ImmStudentattendance (LRN,Name,Gender,Section,Date,TimeIn) VALUES(?,?,?,?,?,?)";
            PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
            preparedStatement.setLong(1, Long.parseLong(resultMap.get("LRN")));
            preparedStatement.setString(2, resultMap.get("Name"));
            preparedStatement.setString(3, resultMap.get("Gender"));
            preparedStatement.setString(4, resultMap.get("Section"));
            preparedStatement.setString(5, currentDate.format(dateFormatter));
            preparedStatement.setString(6, currentDateTime.format(dateTimeFormatter));
            preparedStatement.executeUpdate();
            popUpHeader="TimeIn";
            popUpMessage = "Time in at " + currentDateTime.format(dateTimeFormatter);
            color = Color.GREEN;
            
            try {
                String[] recipients = getEmailRecipients(resultMap.get("Section"));
                sendEmail(recipients, "Time In Confirmation",
                        "Student: " + resultMap.get("Name") + 
                        "\nSection: " + resultMap.get("Section") +
                        "\nLRN: " + resultMap.get("LRN") +
                        "\nClocked in at: " + currentDateTime.format(dateTimeFormatter));
            } catch (Exception e) {
                System.err.println("Email notification failed, but attendance recorded successfully");
            }
        }
        
        lblTimeInTimeOut.setHorizontalAlignment(JLabel.CENTER);
        lblTimeInTimeOut.setText(popUpHeader);
        lblTimeInTimeOut.setForeground(color);
        lblTimeInTimeOut.setBackground(Color.darkGray);
        lblTimeInTimeOut.setOpaque(true);
        showPopUpForCertainDuration(popUpMessage, popUpHeader, JOptionPane.INFORMATION_MESSAGE);
        return true;
        
        
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        if (imagee != null) {
            g.drawImage(imagee, 0, 0, null);
        }
    }
}

    


