/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import com.mysql.cj.result.Row;
import dao.ConnectionProvider;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import utility.BDutility;
import java.sql.PreparedStatement;
import org.apache.poi.xssf.usermodel.XSSFRow;

/**
 *
 * @author Sexon
 */
public class ViewAttendance extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewAttendance.class.getName());

    /**
     * Creates new form ViewAttendance
     */
    public ViewAttendance() {
        initComponents();
        BDutility.setImage(this, "images/registrationBG.png",1010, 510);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(2,2,2,2, Color.GRAY));
        
        dateChooserFrom.setDateFormatString("yyyy-MM-dd");
        dateChooserTo.setDateFormatString("yyyy-MM-dd");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExistRegis = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        dateChooserTo = new com.toedter.calendar.JDateChooser();
        dateChooserFrom = new com.toedter.calendar.JDateChooser();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalH_lbl = new javax.swing.JLabel();
        totalHours = new javax.swing.JLabel();
        remainingH_lbl = new javax.swing.JLabel();
        remainingHours = new javax.swing.JLabel();
        resetFilter = new javax.swing.JButton();
        generatebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("view ATTENDANCE");

        btnExistRegis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExistRegis.setText("X");
        btnExistRegis.setBorder(null);
        btnExistRegis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExistRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExistRegisActionPerformed(evt);
            }
        });

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        UserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(UserTable);

        dateChooserTo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dateChooserTo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChooserToPropertyChange(evt);
            }
        });

        dateChooserFrom.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dateChooserFrom.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChooserFromPropertyChange(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("From:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("To:");

        totalH_lbl.setForeground(new java.awt.Color(0, 255, 0));
        totalH_lbl.setText("Total Hours: ");

        totalHours.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalHours.setForeground(new java.awt.Color(255, 255, 255));
        totalHours.setText("----------------");

        remainingH_lbl.setForeground(new java.awt.Color(204, 0, 0));
        remainingH_lbl.setText("Remaining Hours: ");

        remainingHours.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        remainingHours.setForeground(new java.awt.Color(255, 255, 255));
        remainingHours.setText("----------- ");

        resetFilter.setBackground(new java.awt.Color(255, 0, 0));
        resetFilter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resetFilter.setForeground(new java.awt.Color(255, 255, 255));
        resetFilter.setText("Reset");
        resetFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetFilterActionPerformed(evt);
            }
        });

        generatebtn.setBackground(new java.awt.Color(153, 153, 153));
        generatebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        generatebtn.setForeground(new java.awt.Color(0, 0, 0));
        generatebtn.setText("Generate Report");
        generatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(296, 296, 296)
                        .addComponent(btnExistRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(223, 223, 223))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalH_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalHours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(remainingH_lbl)
                                .addGap(14, 14, 14)
                                .addComponent(remainingHours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(resetFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExistRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateChooserFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateChooserTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalH_lbl)
                            .addComponent(totalHours))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(remainingH_lbl)
                            .addComponent(remainingHours))
                        .addGap(18, 18, 18)
                        .addComponent(resetFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generatebtn)))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExistRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExistRegisActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExistRegisActionPerformed

    private void resetFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetFilterActionPerformed
        
        txtSearch.setText("");
        dateChooserFrom.setDate(null);
        dateChooserTo.setDate(null);
        
        loadDataInTable();
        
    }//GEN-LAST:event_resetFilterActionPerformed

    private void generatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebtnActionPerformed
      int selectedRow = UserTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                "Please select a student from the table first.",
                "No Selection", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String studentLRN = UserTable.getValueAt(selectedRow, 0).toString();
        String studentName = UserTable.getValueAt(selectedRow, 1).toString();
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Immersion Report");
        fileChooser.setSelectedFile(new File(studentName.replace(" ", "_") + "_Immersion_Report.xlsx"));
        
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                createExcelReport(studentLRN, fileChooser.getSelectedFile());
                JOptionPane.showMessageDialog(this, 
                    "Report generated successfully!",
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                int choice = JOptionPane.showConfirmDialog(this, 
                    "Would you like to open the Excel file now?", 
                    "Open File", 
                    JOptionPane.YES_NO_OPTION);
                
                if (choice == JOptionPane.YES_OPTION) {
                    Desktop.getDesktop().open(fileChooser.getSelectedFile());
                }
                
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, 
                    "Error generating report: " + ex.getMessage(),
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_generatebtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        loadDataInTable();
    }//GEN-LAST:event_formComponentShown

    private void UserTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTableMouseClicked
        int selectedRow = UserTable.getSelectedRow();
        if (selectedRow != -1) {
        String selectedLRN = UserTable.getValueAt(selectedRow, 0).toString(); // Assuming LRN is in column 0
        loadStudentHours(selectedLRN);
        }
    }//GEN-LAST:event_UserTableMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        loadDataInTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void dateChooserFromPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserFromPropertyChange
        loadDataInTable();
    }//GEN-LAST:event_dateChooserFromPropertyChange

    private void dateChooserToPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserToPropertyChange
        loadDataInTable();
    }//GEN-LAST:event_dateChooserToPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewAttendance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable UserTable;
    private javax.swing.JButton btnExistRegis;
    private com.toedter.calendar.JDateChooser dateChooserFrom;
    private com.toedter.calendar.JDateChooser dateChooserTo;
    private javax.swing.JButton generatebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel remainingH_lbl;
    private javax.swing.JLabel remainingHours;
    private javax.swing.JButton resetFilter;
    private javax.swing.JLabel totalH_lbl;
    private javax.swing.JLabel totalHours;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    
    
    
    
    
    private void loadDataInTable() {
    try {
        // Clear table
        DefaultTableModel model = (DefaultTableModel) UserTable.getModel();
        model.setRowCount(0);
        
        // Set columns
        model.setColumnIdentifiers(new String[]{
            "LRN", "Name","Gender", "Section", "Date", "Time In", "Time Out", "Work Duration"
        });
        
        Connection con = ConnectionProvider.getCon();
        
        // Build query
        StringBuilder sqlQuery = new StringBuilder();
        sqlQuery.append("SELECT ud.LRN, ud.Name, ud.Gender, ud.Section, ua.Date, ua.TimeIn, ua.TimeOut, ua.workduration ");
        sqlQuery.append("FROM ImmStudentdetails AS ud ");
        sqlQuery.append("INNER JOIN ImmStudentattendance AS ua ON ud.LRN = ua.LRN ");

        
        // Get filter values
        String searchText = txtSearch.getText().trim();
        Date fromDateFromCal = dateChooserFrom.getDate();
        Date toDateFromCal = dateChooserTo.getDate();
        
        LocalDate fromDate = null;
        if (fromDateFromCal != null) {
            fromDate = fromDateFromCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        
        LocalDate toDate = null;
        if (toDateFromCal != null) {
            toDate = toDateFromCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        
        
        boolean hasWhere = false;
        
        // Add search filter
        if (!searchText.isEmpty()) {
            sqlQuery.append("WHERE (ud.Name LIKE '%").append(searchText).append("%' OR ud.LRN LIKE '%").append(searchText).append("%' OR ud.Section LIKE '%").append(searchText).append("%') ");
            hasWhere = true;
        }
        
        // Add date filters
        if (fromDate != null && toDate != null) {
            if (hasWhere) {
                sqlQuery.append("AND ");
            } else {
                sqlQuery.append("WHERE ");
                hasWhere = true;
            }
            sqlQuery.append("ua.Date BETWEEN '").append(fromDate).append("' AND '").append(toDate).append("' ");
        } else if (fromDate != null) {
            if (hasWhere) {
                sqlQuery.append("AND ");
            } else {
                sqlQuery.append("WHERE ");
                hasWhere = true;
            }
            sqlQuery.append("ua.Date = '").append(fromDate).append("' ");
        }
        
        sqlQuery.append("ORDER BY ua.Date DESC, ud.Name ASC");
        
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sqlQuery.toString());
        
        // Format date and time
        java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("MMM dd, yyyy");
        java.text.SimpleDateFormat timeFormat = new java.text.SimpleDateFormat("hh:mm a");
        
        double totalHoursSum = 0.0;
        
        while (rs.next()) {
            String lrn = rs.getString("LRN");
            String name = rs.getString("Name");
            String gender = rs.getString("Gender");     
            String section = rs.getString("Section");
            java.sql.Date date = rs.getDate("Date");
            Timestamp timeIn = rs.getTimestamp("TimeIn");
            Timestamp timeOut = rs.getTimestamp("TimeOut");
            String workDuration = rs.getString("workduration");
            
            // Format date
            String formattedDate = dateFormat.format(date);
            
            // Format time in
            String formattedTimeIn = "N/A";
            if (timeIn != null) {
                formattedTimeIn = timeFormat.format(timeIn);
            }
            
            // Format time out
            String formattedTimeOut = "N/A";
            if (timeOut != null) {
                formattedTimeOut = timeFormat.format(timeOut);
            }
            
            // Calculate hours for total
            if (workDuration != null && !workDuration.isEmpty()) {
                try {
                    String[] parts = workDuration.split("Hours");
                    if (parts.length > 0) {
                        double hours = Double.parseDouble(parts[0].trim());
                        totalHoursSum += hours;
                    }
                } catch (Exception e) {
                    // Skip if parsing fails
                }
            }
            
            Object[] row = {
                lrn,
                name,
                gender != null ? gender : "N/A",        // ✅ ADD GENDER IN CORRECT POSITION
                section != null ? section : "N/A",      // ✅ SECTION IN CORRECT POSITION
                formattedDate,
                formattedTimeIn,
                formattedTimeOut,
                workDuration != null ? workDuration : "N/A"
            };
            model.addRow(row);
        }
        
        // Update total hours label
        totalHours.setText(String.format("%.1f hours", totalHoursSum));
        
        // Calculate remaining hours (assuming 180 hours required)
        double remainingHoursValue = Math.max(0, 180.0 - totalHoursSum);
        remainingHours.setText(String.format("%.1f hours", remainingHoursValue));
        
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Database Error: " + ex.getMessage(),
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, 
                "Error: " + ex.getMessage(),
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void loadStudentHours(String lrn) {
    try {
        Connection con = ConnectionProvider.getCon();
        String query = "SELECT workduration FROM ImmStudentattendance WHERE LRN = ?";
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, lrn);
        ResultSet rs = ps.executeQuery();

        double totalHoursValue = 0.0;

        while (rs.next()) {
            String duration = rs.getString("workduration");
            if (duration != null && !duration.isEmpty()) {
                try {
                    String[] parts = duration.split("Hours");
                    if (parts.length > 0) {
                        totalHoursValue += Double.parseDouble(parts[0].trim());
                    }
                } catch (Exception e) {
                    // Skip invalid formats
                }
            }
        }
        //////////////////////////////////////////////////////////////////////////////////////////
        // Update the labels (JLabel components)
        totalHours.setText(String.format("%.1f hours", totalHoursValue));
        double remaining = Math.max(0, 180.0 - totalHoursValue);
        remainingHours.setText(String.format("%.1f hours", remaining));

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
     private void createExcelReport(String studentLRN, File outputFile) throws Exception {
        Connection con = ConnectionProvider.getCon();
        
        String studentQuery = "SELECT * FROM immstudentdetails WHERE LRN = ?";
        PreparedStatement pstStudent = con.prepareStatement(studentQuery);
        pstStudent.setString(1, studentLRN);
        ResultSet rsStudent = pstStudent.executeQuery();
        
        if (!rsStudent.next()) {
            throw new Exception("Student not found");
        }
        
        String name = rsStudent.getString("Name");
        String gender = rsStudent.getString("Gender");
        String section = rsStudent.getString("Section");
        String classAdviser = rsStudent.getString("Adviser");
        
        String attendanceQuery = "SELECT Date, TimeIn, TimeOut, workduration " +
                        "FROM ImmStudentattendance WHERE LRN = ? ORDER BY Date ASC";
        PreparedStatement pstAttendance = con.prepareStatement(
            attendanceQuery,
            ResultSet.TYPE_SCROLL_INSENSITIVE,  // Allows scrolling backward
            ResultSet.CONCUR_READ_ONLY
        );
        pstAttendance.setString(1, studentLRN);
        ResultSet rsAttendance = pstAttendance.executeQuery();
        
        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet sheet = workbook.createSheet("Immersion Report");
        
        CellStyle titleStyle = workbook.createCellStyle();
        Font titleFont = workbook.createFont();
        titleFont.setBold(true);
        titleFont.setFontHeightInPoints((short) 18);
        titleStyle.setFont(titleFont);
        
        CellStyle headerStyle = workbook.createCellStyle();
        Font headerFont = workbook.createFont();
        headerFont.setBold(true);
        headerFont.setFontHeightInPoints((short) 12);
        headerStyle.setFont(headerFont);
        headerStyle.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
        headerStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        
        CellStyle labelStyle = workbook.createCellStyle();
        Font labelFont = workbook.createFont();
        labelFont.setBold(true);
        labelStyle.setFont(labelFont);
        
        int rowNum = 0;
        
        XSSFRow titleRow = sheet.createRow(rowNum++);
        Cell titleCell = titleRow.createCell(0);
        titleCell.setCellValue("WORK IMMERSION ATTENDANCE REPORT");
        titleCell.setCellStyle(titleStyle);
        rowNum++;
        
        sheet.createRow(rowNum++).createCell(0).setCellValue("STUDENT INFORMATION");
        createLabelValueRow(sheet, rowNum++, "LRN:", studentLRN, labelStyle);
        createLabelValueRow(sheet, rowNum++, "Name:", name, labelStyle);
        createLabelValueRow(sheet, rowNum++, "Gender:", gender != null ? gender : "N/A", labelStyle);
        createLabelValueRow(sheet, rowNum++, "Section:", section != null ? section : "N/A", labelStyle);
        createLabelValueRow(sheet, rowNum++, "Class Adviser:", classAdviser != null ? classAdviser : "N/A", labelStyle);
        createLabelValueRow(sheet, rowNum++, "Report Generated:", 
            new SimpleDateFormat("MMM dd, yyyy HH:mm").format(new Date()), labelStyle);
        rowNum++;
        
        Map<String, Double> monthlyHours = new HashMap<>();
        Map<String, Integer> monthlyDays = new HashMap<>();
        double totalHours = 0.0;
        int totalDaysPresent = 0;
        LocalDate firstDate = null;
        LocalDate lastDate = null;
        
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        
        while (rsAttendance.next()) {
            totalDaysPresent++;
            String dateStr = rsAttendance.getString("Date");
            String workDuration = rsAttendance.getString("workduration");
            
            LocalDate date = LocalDate.parse(dateStr, dateFormatter);
            if (firstDate == null || date.isBefore(firstDate)) firstDate = date;
            if (lastDate == null || date.isAfter(lastDate)) lastDate = date;
            
            if (workDuration != null) {
                try {
                    String[] parts = workDuration.split("Hours");
                    double hours = Double.parseDouble(parts[0].trim());
                    totalHours += hours;
                    
                    String monthKey = date.format(DateTimeFormatter.ofPattern("MMMM yyyy"));
                    monthlyHours.put(monthKey, monthlyHours.getOrDefault(monthKey, 0.0) + hours);
                    monthlyDays.put(monthKey, monthlyDays.getOrDefault(monthKey, 0) + 1);
                } catch (Exception e) {
                }
            }
        }
        
        int totalAbsences = 0;
        if (firstDate != null && lastDate != null) {
            totalAbsences = countWeekdays(firstDate, lastDate) - totalDaysPresent;
        }
        
        sheet.createRow(rowNum++).createCell(0).setCellValue("IMMERSION SUMMARY");
        createLabelValueRow(sheet, rowNum++, "Total Required Hours:", "180 hours", labelStyle);
        createLabelValueRow(sheet, rowNum++, "Total Hours Completed:", String.format("%.1f hours", totalHours), labelStyle);
        createLabelValueRow(sheet, rowNum++, "Hours Remaining:", String.format("%.1f hours", Math.max(0, 180.0 - totalHours)), labelStyle);
        createLabelValueRow(sheet, rowNum++, "Completion Percentage:", String.format("%.1f%%", (totalHours / 180.0) * 100), labelStyle);
        createLabelValueRow(sheet, rowNum++, "Total Days Present:", String.valueOf(totalDaysPresent), labelStyle);
        createLabelValueRow(sheet, rowNum++, "Total Absences:", String.valueOf(totalAbsences), labelStyle);
        
        if (firstDate != null && lastDate != null) {
            createLabelValueRow(sheet, rowNum++, "First Immersion Day:", 
                firstDate.format(DateTimeFormatter.ofPattern("MMM dd, yyyy")), labelStyle);
            createLabelValueRow(sheet, rowNum++, "Last Immersion Day:", 
                lastDate.format(DateTimeFormatter.ofPattern("MMM dd, yyyy")), labelStyle);
            createLabelValueRow(sheet, rowNum++, "Total Duration:", 
                ChronoUnit.DAYS.between(firstDate, lastDate) + 1 + " days", labelStyle);
        }
        rowNum++;
        
        if (!monthlyHours.isEmpty()) {
            sheet.createRow(rowNum++).createCell(0).setCellValue("MONTHLY BREAKDOWN");
            XSSFRow monthHeaderRow = sheet.createRow(rowNum++);
            
            Cell monthCell = monthHeaderRow.createCell(0);
            monthCell.setCellValue("Month");
            monthCell.setCellStyle(headerStyle);
            
            Cell daysCell = monthHeaderRow.createCell(1);
            daysCell.setCellValue("Days Present");
            daysCell.setCellStyle(headerStyle);
            
            Cell hoursCell = monthHeaderRow.createCell(2);
            hoursCell.setCellValue("Hours Completed");
            hoursCell.setCellStyle(headerStyle);
            
            for (Map.Entry<String, Double> entry : monthlyHours.entrySet()) {
                XSSFRow monthRow = sheet.createRow(rowNum++);
                monthRow.createCell(0).setCellValue(entry.getKey());
                monthRow.createCell(1).setCellValue(monthlyDays.getOrDefault(entry.getKey(), 0));
                monthRow.createCell(2).setCellValue(String.format("%.1f hours", entry.getValue()));
            }
            rowNum++;
        }
        
        sheet.createRow(rowNum++).createCell(0).setCellValue("DETAILED ATTENDANCE RECORDS");
        XSSFRow headerRow = sheet.createRow(rowNum++);
        String[] headers = {"Date", "Day", "Time In", "Time Out", "Work Duration", "Status"};
        for (int i = 0; i < headers.length; i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(headerStyle);
        }
        
        rsAttendance.beforeFirst();
        
        SimpleDateFormat displayFormat = new SimpleDateFormat("MMM dd, yyyy");
        SimpleDateFormat dayFormat = new SimpleDateFormat("EEEE");
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("h:mm a");
        
        while (rsAttendance.next()) {
            XSSFRow dataRow = sheet.createRow(rowNum++);
            
            String dateStr = rsAttendance.getString("Date");
            String timeIn = rsAttendance.getString("TimeIn");
            String timeOut = rsAttendance.getString("TimeOut");
            String workDuration = rsAttendance.getString("workduration");
            
            java.sql.Date sqlDate = java.sql.Date.valueOf(dateStr);
            String formattedDate = displayFormat.format(sqlDate);
            String dayOfWeek = dayFormat.format(sqlDate);
            
            String formattedTimeIn = "";
            String formattedTimeOut = "";
            String status = "Present";
            
            if (timeIn != null) {
                LocalDateTime timeInDateTime = LocalDateTime.parse(timeIn, 
                    DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                formattedTimeIn = timeInDateTime.format(timeFormatter);
                
                if (timeInDateTime.getHour() >= 9) {
                    status = "Late";
                }
            }
            
            if (timeOut != null) {
                LocalDateTime timeOutDateTime = LocalDateTime.parse(timeOut, 
                    DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                formattedTimeOut = timeOutDateTime.format(timeFormatter);
            } else {
                formattedTimeOut = "Not recorded";
            }
            
            dataRow.createCell(0).setCellValue(formattedDate);
            dataRow.createCell(1).setCellValue(dayOfWeek);
            dataRow.createCell(2).setCellValue(formattedTimeIn);
            dataRow.createCell(3).setCellValue(formattedTimeOut);
            dataRow.createCell(4).setCellValue(workDuration != null ? workDuration : "Incomplete");
            dataRow.createCell(5).setCellValue(status);
        }
        
        for (int i = 0; i < 6; i++) {
            sheet.autoSizeColumn(i);
        }
        
        try (FileOutputStream fileOut = new FileOutputStream(outputFile)) {
            workbook.write(fileOut);
        }
        
        workbook.close();
    }
    
    private void createLabelValueRow(XSSFSheet sheet, int rowNum, String label, String value, CellStyle labelStyle) {
        XSSFRow row = sheet.createRow(rowNum);
        Cell labelCell = row.createCell(0);
        labelCell.setCellValue(label);
        labelCell.setCellStyle(labelStyle);
        row.createCell(1).setCellValue(value);
    }
    
    private int countWeekdays(LocalDate start, LocalDate end) {
        int count = 0;
        LocalDate date = start;
        while (date.isBefore(end) || date.equals(end)) {
            if (!(date.getDayOfWeek() == DayOfWeek.SATURDAY || date.getDayOfWeek() == DayOfWeek.SUNDAY)) {
                count++;
            }
            date = date.plusDays(1);
        }
        return count;
    }
    
}