/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import com.mysql.cj.result.Row;
import dao.ConnectionProvider;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import utility.BDutility;
import java.sql.PreparedStatement;
import org.apache.poi.xssf.usermodel.XSSFRow;

/**
 *
 * @author Sexon
 */
public class ViewAttendance extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewAttendance.class.getName());

    /**
     * Creates new form ViewAttendance
     */
    public ViewAttendance() {
        initComponents();
        BDutility.setImage(this, "images/registrationBG.png",1005, 480);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(2,2,2,2, Color.GRAY));
        
        dateChooserFrom.setDateFormatString("yyyy-MM-dd");
        dateChooserTo.setDateFormatString("yyyy-MM-dd");
        
        loadWorkplacesIntoComboBox();
        comboWorkplace.setSelectedIndex(0);
        loadDataInTable();
        loadFilteredAttendanceCount();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExistRegis = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        dateChooserTo = new com.toedter.calendar.JDateChooser();
        dateChooserFrom = new com.toedter.calendar.JDateChooser();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalH_lbl = new javax.swing.JLabel();
        totalHours = new javax.swing.JLabel();
        remainingH_lbl = new javax.swing.JLabel();
        remainingHours = new javax.swing.JLabel();
        resetFilter = new javax.swing.JButton();
        generatebtn = new javax.swing.JButton();
        comboWorkplace = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnToday = new javax.swing.JButton();
        totalH_lbl1 = new javax.swing.JLabel();
        attendanceCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("view ATTENDANCE");

        btnExistRegis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExistRegis.setText("X");
        btnExistRegis.setBorder(null);
        btnExistRegis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExistRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExistRegisActionPerformed(evt);
            }
        });

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        UserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(UserTable);

        dateChooserTo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dateChooserTo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChooserToPropertyChange(evt);
            }
        });

        dateChooserFrom.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        dateChooserFrom.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChooserFromPropertyChange(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("From:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("To:");

        totalH_lbl.setForeground(new java.awt.Color(0, 255, 0));
        totalH_lbl.setText("Total Hours: ");

        totalHours.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalHours.setForeground(new java.awt.Color(255, 255, 255));
        totalHours.setText("----------------");

        remainingH_lbl.setForeground(new java.awt.Color(204, 0, 0));
        remainingH_lbl.setText("Remaining Hours: ");

        remainingHours.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        remainingHours.setForeground(new java.awt.Color(255, 255, 255));
        remainingHours.setText("----------- ");

        resetFilter.setBackground(new java.awt.Color(255, 0, 0));
        resetFilter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resetFilter.setForeground(new java.awt.Color(255, 255, 255));
        resetFilter.setText("Show All");
        resetFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetFilterActionPerformed(evt);
            }
        });

        generatebtn.setBackground(new java.awt.Color(255, 255, 0));
        generatebtn.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        generatebtn.setForeground(new java.awt.Color(0, 0, 0));
        generatebtn.setText("Generate Report");
        generatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebtnActionPerformed(evt);
            }
        });

        comboWorkplace.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Item 2", "Item 3", "Item 4" }));
        comboWorkplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboWorkplaceActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Company:");

        btnToday.setBackground(new java.awt.Color(255, 0, 0));
        btnToday.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnToday.setForeground(new java.awt.Color(255, 255, 255));
        btnToday.setText("Today");
        btnToday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodayActionPerformed(evt);
            }
        });

        totalH_lbl1.setForeground(new java.awt.Color(0, 255, 204));
        totalH_lbl1.setText("Attendance Count:");

        attendanceCount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        attendanceCount.setForeground(new java.awt.Color(255, 255, 255));
        attendanceCount.setText("----------- ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(296, 296, 296)
                        .addComponent(btnExistRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(comboWorkplace, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel3)
                                        .addGap(115, 115, 115)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(btnToday, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(resetFilter)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalH_lbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(attendanceCount))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalH_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalHours))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(remainingH_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remainingHours))
                            .addComponent(generatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExistRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(comboWorkplace))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dateChooserFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dateChooserTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(resetFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnToday, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalH_lbl1)
                            .addComponent(attendanceCount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalH_lbl)
                            .addComponent(totalHours))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(remainingH_lbl)
                            .addComponent(remainingHours))
                        .addGap(150, 150, 150)
                        .addComponent(generatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExistRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExistRegisActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExistRegisActionPerformed

    private void resetFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetFilterActionPerformed
        comboWorkplace.setSelectedIndex(0); 
        txtSearch.setText("");
        dateChooserFrom.setDate(null);
        dateChooserTo.setDate(null);

        DefaultTableModel model = (DefaultTableModel) UserTable.getModel();
        model.setRowCount(0); // clear table

        loadDataInTable(); // reload all records
        loadFilteredAttendanceCount(); // refresh stats

        JOptionPane.showMessageDialog(this,
            "Showing all attendance records.",
            "Show All",
            JOptionPane.INFORMATION_MESSAGE);

        
    }//GEN-LAST:event_resetFilterActionPerformed

    private void generatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebtnActionPerformed
      int selectedRow = UserTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                "Please select a student from the table first.",
                "No Selection", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String studentLRN = UserTable.getValueAt(selectedRow, 0).toString();
        String studentName = UserTable.getValueAt(selectedRow, 1).toString();
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Save Immersion Report");
        fileChooser.setSelectedFile(new File(studentName.replace(" ", "_") + "_Immersion_Report.xlsx"));
        
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                createExcelReport(studentLRN, fileChooser.getSelectedFile());
                JOptionPane.showMessageDialog(this, 
                    "Report generated successfully!",
                    "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                int choice = JOptionPane.showConfirmDialog(this, 
                    "Would you like to open the Excel file now?", 
                    "Open File", 
                    JOptionPane.YES_NO_OPTION);
                
                if (choice == JOptionPane.YES_OPTION) {
                    Desktop.getDesktop().open(fileChooser.getSelectedFile());
                }
                
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, 
                    "Error generating report: " + ex.getMessage(),
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_generatebtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Date today = new Date();
        dateChooserFrom.setDate(today);
        dateChooserTo.setDate(today);
    
        loadDataInTable();
        
        
    }//GEN-LAST:event_formComponentShown

    private void UserTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTableMouseClicked
        int selectedRow = UserTable.getSelectedRow();
        if (selectedRow != -1) {
        String selectedLRN = UserTable.getValueAt(selectedRow, 0).toString(); // Assuming LRN is in column 0
        loadStudentHours(selectedLRN);
        }
    }//GEN-LAST:event_UserTableMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        loadDataInTable();
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        loadDataInTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void dateChooserFromPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserFromPropertyChange
        loadDataInTable();
    }//GEN-LAST:event_dateChooserFromPropertyChange

    private void dateChooserToPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserToPropertyChange
        loadDataInTable();
    }//GEN-LAST:event_dateChooserToPropertyChange

    private void comboWorkplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboWorkplaceActionPerformed
            
       Object selectedItem = comboWorkplace.getSelectedItem();
       if (selectedItem == null) {
           return; // Exit early if nothing is selected
       }

       String selectedWorkplace = selectedItem.toString();

       DefaultTableModel model = (DefaultTableModel) UserTable.getModel();
       model.setRowCount(0); 

       String sql;
       if (selectedWorkplace.equals("All Workplaces")) {
           sql = "SELECT ud.LRN, ud.Name, ud.Gender, ud.Section, ud.workplace, " +
                 "ua.Date, ua.TimeIn, ua.TimeOut, ua.workduration " +
                 "FROM ImmStudentdetails AS ud " +
                 "INNER JOIN ImmStudentattendance AS ua ON ud.LRN = ua.LRN " +
                 "ORDER BY ua.Date DESC";
       } else {
           sql = "SELECT ud.LRN, ud.Name, ud.Gender, ud.Section, ud.workplace, " +
                 "ua.Date, ua.TimeIn, ua.TimeOut, ua.workduration " +
                 "FROM ImmStudentdetails AS ud " +
                 "INNER JOIN ImmStudentattendance AS ua ON ud.LRN = ua.LRN " +
                 "WHERE ud.workplace = ? ORDER BY ua.Date DESC";
       }

       try (Connection con = ConnectionProvider.getCon();
            PreparedStatement pst = con.prepareStatement(sql)) {
           if (!selectedWorkplace.equals("All Workplaces")) {
               pst.setString(1, selectedWorkplace);
           }

           ResultSet rs = pst.executeQuery();
           SimpleDateFormat dateFormat = new SimpleDateFormat("MMM dd, yyyy");
           SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm a");

           while (rs.next()) {
               String lrn = rs.getString("LRN");
               String name = rs.getString("Name");
               String gender = rs.getString("Gender");
               String section = rs.getString("Section");
               String workplace = rs.getString("workplace");
               Date date = rs.getDate("Date");
               Timestamp timeIn = rs.getTimestamp("TimeIn");
               Timestamp timeOut = rs.getTimestamp("TimeOut");
               String workDuration = rs.getString("workduration");

               String formattedDate = dateFormat.format(date);
               String formattedTimeIn = (timeIn != null) ? timeFormat.format(timeIn) : "N/A";
               String formattedTimeOut = (timeOut != null) ? timeFormat.format(timeOut) : "N/A";

               model.addRow(new Object[]{
                   lrn,
                   name,
                   gender != null ? gender : "N/A",
                   section != null ? section : "N/A",
                   workplace != null ? workplace : "N/A",
                   formattedDate,
                   formattedTimeIn,
                   formattedTimeOut,
                   workDuration != null ? workDuration : "N/A"
               });
           }
       } catch (Exception ex) {
           ex.printStackTrace();
           JOptionPane.showMessageDialog(this, "Error loading data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
       }
       loadDataInTable();
    }//GEN-LAST:event_comboWorkplaceActionPerformed

    private void btnTodayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodayActionPerformed
        Date today = new Date();
        dateChooserFrom.setDate(today);
        dateChooserTo.setDate(today);
    
    // Reload table with today's data
    loadDataInTable();
    
    JOptionPane.showMessageDialog(this, 
        "Showing today's attendance records", 
        "Today Filter Applied", 
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTodayActionPerformed
    
    private void loadWorkplacesIntoComboBox() {
    java.awt.event.ActionListener[] listeners = comboWorkplace.getActionListeners();
    for (java.awt.event.ActionListener listener : listeners) {
        comboWorkplace.removeActionListener(listener);
    }
    
    comboWorkplace.removeAllItems();
    comboWorkplace.addItem("All Workplaces"); 

    try (Connection con = ConnectionProvider.getCon();
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery("SELECT DISTINCT workplace FROM ImmStudentdetails WHERE workplace IS NOT NULL")) {
        while (rs.next()) {
            String workplace = rs.getString("workplace");
            if (workplace != null && !workplace.trim().isEmpty()) {
                comboWorkplace.addItem(workplace);
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    
    if (comboWorkplace.getItemCount() > 0) { 
        comboWorkplace.setSelectedIndex(0); 
    }
    
    // ⭐ Re-add the action listeners
    for (java.awt.event.ActionListener listener : listeners) {
        comboWorkplace.addActionListener(listener);
    }
}
     
    private void loadFilteredAttendanceCount() {
    try (Connection con = ConnectionProvider.getCon()) {
        StringBuilder sql = new StringBuilder(
            "SELECT COUNT(*) AS countFiltered " +
            "FROM ImmStudentdetails AS ud " +
            "INNER JOIN ImmStudentattendance AS ua ON ud.LRN = ua.LRN "
        );

        String searchText = txtSearch.getText().trim();
        Date fromDateFromCal = dateChooserFrom.getDate();
        Date toDateFromCal = dateChooserTo.getDate();
        Object selected = comboWorkplace.getSelectedItem();

        LocalDate fromDate = null;
        if (fromDateFromCal != null) {
            fromDate = fromDateFromCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }

        LocalDate toDate = null;
        if (toDateFromCal != null) {
            toDate = toDateFromCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }

        boolean hasWhere = false;

        if (!searchText.isEmpty()) {
            sql.append("WHERE (ud.Name LIKE '%").append(searchText)
               .append("%' OR ud.LRN LIKE '%").append(searchText).append("%') ");
            hasWhere = true;
        }

        if (selected != null && !"All Workplaces".equals(selected.toString())) {
            sql.append(hasWhere ? "AND " : "WHERE ");
            sql.append("ud.workplace = '").append(selected.toString()).append("' ");
            hasWhere = true;
        }

        if (fromDate != null && toDate != null) {
            sql.append(hasWhere ? "AND " : "WHERE ");
            sql.append("ua.Date BETWEEN '").append(fromDate).append("' AND '").append(toDate).append("' ");
        } else if (fromDate != null) {
            sql.append(hasWhere ? "AND " : "WHERE ");
            sql.append("ua.Date = '").append(fromDate).append("' ");
        }

        sql.append("AND ua.TimeIn IS NOT NULL");

        try (Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(sql.toString())) {
            if (rs.next()) {
                int count = rs.getInt("countFiltered");
                attendanceCount.setText(""+ count);
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        attendanceCount.setText("Attendance Count: Error");
    }
}




    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewAttendance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable UserTable;
    private javax.swing.JLabel attendanceCount;
    private javax.swing.JButton btnExistRegis;
    private javax.swing.JButton btnToday;
    private javax.swing.JComboBox<String> comboWorkplace;
    private com.toedter.calendar.JDateChooser dateChooserFrom;
    private com.toedter.calendar.JDateChooser dateChooserTo;
    private javax.swing.JButton generatebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel remainingH_lbl;
    private javax.swing.JLabel remainingHours;
    private javax.swing.JButton resetFilter;
    private javax.swing.JLabel totalH_lbl;
    private javax.swing.JLabel totalH_lbl1;
    private javax.swing.JLabel totalHours;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    
    
    
    
    
    private void loadDataInTable() {
    try {
        DefaultTableModel model = (DefaultTableModel) UserTable.getModel();
        model.setRowCount(0);

        model.setColumnIdentifiers(new String[]{
            "LRN", "Name", "Gender", "Section", "Work Place", "Date", "Time In", "Time Out", "Work Duration"
        });

        Connection con = ConnectionProvider.getCon();

        StringBuilder sqlQuery = new StringBuilder();
        sqlQuery.append(
            "SELECT ud.LRN, ud.Name, ud.Gender, ud.Section, ud.workplace, " +
            "ua.Date, ua.TimeIn, ua.TimeOut, ua.workduration " +
            "FROM ImmStudentdetails AS ud " +
            "INNER JOIN ImmStudentattendance AS ua ON ud.LRN = ua.LRN "
        );

        String searchText = txtSearch.getText().trim();
        Date fromDateFromCal = dateChooserFrom.getDate();
        Date toDateFromCal = dateChooserTo.getDate();
        Object selected = comboWorkplace.getSelectedItem();

        LocalDate fromDate = null;
        if (fromDateFromCal != null) {
            fromDate = fromDateFromCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }

        LocalDate toDate = null;
        if (toDateFromCal != null) {
            toDate = toDateFromCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }

        boolean hasWhere = false;

        if (!searchText.isEmpty()) {
            sqlQuery.append("WHERE (ud.Name LIKE '%").append(searchText) 
                    .append("%' OR ud.LRN LIKE '%").append(searchText) 
                    .append("%' OR ud.Gender LIKE '%").append(searchText) 
                    .append("%' OR ud.Section LIKE '%").append(searchText) 
                    .append("%' OR ud.workplace LIKE '%").append(searchText).append("%') ");
            hasWhere = true;
        }
        
        if (selected != null && !"All Workplaces".equals(selected.toString())) { 
            sqlQuery.append(hasWhere ? "AND " : "WHERE "); 
            sqlQuery.append("ud.workplace = '").append(selected.toString()).append("' "); 
            hasWhere = true; 
        }

        if (fromDate != null && toDate != null) {
            if (hasWhere) {
                sqlQuery.append("AND ");
            } else {
                sqlQuery.append("WHERE ");
                hasWhere = true;
            }
            sqlQuery.append("ua.Date BETWEEN '").append(fromDate).append("' AND '").append(toDate).append("' ");
        } else if (fromDate != null) {
            if (hasWhere) {
                sqlQuery.append("AND ");
            } else {
                sqlQuery.append("WHERE ");
                hasWhere = true;
            }
            sqlQuery.append("ua.Date = '").append(fromDate).append("' ");
        }

        sqlQuery.append("ORDER BY ua.Date DESC, ud.Name ASC");

        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sqlQuery.toString());

        SimpleDateFormat dateFormat = new SimpleDateFormat("MMM dd, yyyy");
        SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm a");

        while (rs.next()) {
            String lrn = rs.getString("LRN");
            String name = rs.getString("Name");
            String gender = rs.getString("Gender");
            String section = rs.getString("Section");
            String workplace = rs.getString("workplace");
            Date date = rs.getDate("Date");
            Timestamp timeIn = rs.getTimestamp("TimeIn");
            Timestamp timeOut = rs.getTimestamp("TimeOut");
            String workDuration = rs.getString("workduration");

            String formattedDate = dateFormat.format(date);
            String formattedTimeIn = (timeIn != null) ? timeFormat.format(timeIn) : "N/A";
            String formattedTimeOut = (timeOut != null) ? timeFormat.format(timeOut) : "N/A";

            Object[] row = {
                lrn,
                name,
                gender != null ? gender : "N/A",
                section != null ? section : "N/A",
                workplace != null ? workplace : "N/A",
                formattedDate,
                formattedTimeIn,
                formattedTimeOut,
                workDuration != null ? workDuration : "N/A"
            };
            model.addRow(row);
        }

        // ⭐ RESET HOURS DISPLAY WHEN TABLE IS RELOADED
        totalHours.setText("Pick a St");
        remainingHours.setText("Pick a St");

        rs.close();
        st.close();

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    loadFilteredAttendanceCount();
}

    
    private void loadStudentHours(String lrn) {
    try {
        Connection con = ConnectionProvider.getCon();
        String query = "SELECT workduration FROM ImmStudentattendance WHERE LRN = ?";
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, lrn);
        ResultSet rs = ps.executeQuery();

        double totalHoursValue = 0.0;

        while (rs.next()) {
            String duration = rs.getString("workduration");
            if (duration != null && !duration.isEmpty()) {
                try {
                    // Extract hours from "XHours and YMinutes" format
                    String[] parts = duration.split("Hours");
                    if (parts.length > 0) {
                        double hours = Double.parseDouble(parts[0].trim());
                        totalHoursValue += hours;
                        
                        // Also add minutes if present
                        if (parts.length > 1 && parts[1].contains("and")) {
                            String minutesPart = parts[1].trim();
                            if (minutesPart.startsWith("and")) {
                                minutesPart = minutesPart.substring(3).trim(); // Remove "and "
                                String[] minuteParts = minutesPart.split("Minutes");
                                if (minuteParts.length > 0) {
                                    double minutes = Double.parseDouble(minuteParts[0].trim());
                                    totalHoursValue += (minutes / 60.0); // Convert minutes to hours
                                }
                            }
                        }
                    }
                } catch (NumberFormatException e) {
                    System.err.println("Error parsing duration: " + duration);
                    e.printStackTrace();
                }
            }
        }

        rs.close();
        ps.close();

        totalHours.setText(String.format("%.1f hours", totalHoursValue));
        double remaining = Math.max(0, 160.0 - totalHoursValue);
        remainingHours.setText(String.format("%.1f hours", remaining));
        

        System.out.println("LRN: " + lrn + " | Total Hours: " + totalHoursValue + " | Remaining: " + remaining);

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        

        totalHours.setText("Error");
        remainingHours.setText("Error");
    }
    }
    
     private void createExcelReport(String studentLRN, File outputFile) throws Exception {
        Connection con = ConnectionProvider.getCon();
    
            String studentQuery = "SELECT * FROM immstudentdetails WHERE LRN = ?";
            PreparedStatement pstStudent = con.prepareStatement(studentQuery);
            pstStudent.setString(1, studentLRN);
            ResultSet rsStudent = pstStudent.executeQuery();

            if (!rsStudent.next()) {
                throw new Exception("Student not found");
            }

            String name = rsStudent.getString("Name");
            String gender = rsStudent.getString("Gender");
            String section = rsStudent.getString("Section");
            String classAdviser = rsStudent.getString("Adviser");
            String workplace = rsStudent.getString("workplace");

            String attendanceQuery = "SELECT Date, TimeIn, TimeOut, workduration " +
                            "FROM ImmStudentattendance WHERE LRN = ? ORDER BY Date ASC";
            PreparedStatement pstAttendance = con.prepareStatement(
                attendanceQuery,
                ResultSet.TYPE_SCROLL_INSENSITIVE,
                ResultSet.CONCUR_READ_ONLY
            );
            pstAttendance.setString(1, studentLRN);
            ResultSet rsAttendance = pstAttendance.executeQuery();

            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet sheet = workbook.createSheet("Immersion Report");

            CellStyle titleStyle = workbook.createCellStyle();
            Font titleFont = workbook.createFont();
            titleFont.setBold(true);
            titleFont.setFontHeightInPoints((short) 18);
            titleStyle.setFont(titleFont);

            CellStyle headerStyle = workbook.createCellStyle();
            Font headerFont = workbook.createFont();
            headerFont.setBold(true);
            headerFont.setFontHeightInPoints((short) 12);
            headerStyle.setFont(headerFont);
            headerStyle.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
            headerStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

            CellStyle labelStyle = workbook.createCellStyle();
            Font labelFont = workbook.createFont();
            labelFont.setBold(true);
            labelStyle.setFont(labelFont);

            int rowNum = 0;

            XSSFRow titleRow = sheet.createRow(rowNum++);
            Cell titleCell = titleRow.createCell(0);
            titleCell.setCellValue("WORK IMMERSION ATTENDANCE REPORT");
            titleCell.setCellStyle(titleStyle);
            rowNum++;

            sheet.createRow(rowNum++).createCell(0).setCellValue("STUDENT INFORMATION");
            createLabelValueRow(sheet, rowNum++, "LRN:", studentLRN, labelStyle);
            createLabelValueRow(sheet, rowNum++, "Name:", name, labelStyle);
            createLabelValueRow(sheet, rowNum++, "Gender:", gender != null ? gender : "N/A", labelStyle);
            createLabelValueRow(sheet, rowNum++, "Section:", section != null ? section : "N/A", labelStyle);
            createLabelValueRow(sheet, rowNum++, "Class Adviser:", classAdviser != null ? classAdviser : "N/A", labelStyle);
            createLabelValueRow(sheet, rowNum++, "Work Place:", workplace != null ? workplace : "N/A", labelStyle);
            createLabelValueRow(sheet, rowNum++, "Report Generated:", 
                new SimpleDateFormat("MMM dd, yyyy HH:mm").format(new Date()), labelStyle);
            rowNum++;

            Map<String, Double> monthlyHours = new HashMap<>();
            Map<String, Integer> monthlyDays = new HashMap<>();
            double totalHours = 0.0;
            int totalDaysPresent = 0;
            LocalDate firstDate = null;
            LocalDate lastDate = null;

            DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

            // ============================================================================
            // FIXED: Properly calculate hours including minutes
            // ============================================================================
            while (rsAttendance.next()) {
                totalDaysPresent++;
                String dateStr = rsAttendance.getString("Date");
                String workDuration = rsAttendance.getString("workduration");

                LocalDate date = LocalDate.parse(dateStr, dateFormatter);
                if (firstDate == null || date.isBefore(firstDate)) firstDate = date;
                if (lastDate == null || date.isAfter(lastDate)) lastDate = date;

                if (workDuration != null && !workDuration.isEmpty()) {
                    try {
                        double hoursDecimal = 0.0;

                        // Parse "XHours and YMinutes" format
                        if (workDuration.contains("Hours")) {
                            String[] hoursPart = workDuration.split("Hours");
                            if (hoursPart.length > 0) {
                                hoursDecimal += Double.parseDouble(hoursPart[0].trim());
                            }

                            // Parse minutes if present
                            if (hoursPart.length > 1 && hoursPart[1].contains("and")) {
                                String minutesPart = hoursPart[1].trim();
                                if (minutesPart.startsWith("and")) {
                                    minutesPart = minutesPart.substring(3).trim(); // Remove "and "
                                    if (minutesPart.contains("Minutes")) {
                                        String[] minParts = minutesPart.split("Minutes");
                                        if (minParts.length > 0) {
                                            double minutes = Double.parseDouble(minParts[0].trim());
                                            hoursDecimal += (minutes / 60.0); // Convert to hours
                                        }
                                    }
                                }
                            }
                        }

                        totalHours += hoursDecimal;

                        String monthKey = date.format(DateTimeFormatter.ofPattern("MMMM yyyy"));
                        monthlyHours.put(monthKey, monthlyHours.getOrDefault(monthKey, 0.0) + hoursDecimal);
                        monthlyDays.put(monthKey, monthlyDays.getOrDefault(monthKey, 0) + 1);

                    } catch (NumberFormatException e) {
                        System.err.println("Error parsing work duration: " + workDuration);
                        e.printStackTrace();
                    }
                }
            }

            int totalAbsences = 0;
            if (firstDate != null && lastDate != null) {
                totalAbsences = countWeekdays(firstDate, lastDate) - totalDaysPresent;
            }

            sheet.createRow(rowNum++).createCell(0).setCellValue("IMMERSION SUMMARY");
            createLabelValueRow(sheet, rowNum++, "Total Required Hours:", "160 hours", labelStyle);
            createLabelValueRow(sheet, rowNum++, "Total Hours Completed:", String.format("%.1f hours", totalHours), labelStyle);
            createLabelValueRow(sheet, rowNum++, "Hours Remaining:", String.format("%.1f hours", Math.max(0, 160.0 - totalHours)), labelStyle);
            createLabelValueRow(sheet, rowNum++, "Completion Percentage:", String.format("%.1f%%", (totalHours / 160.0) * 100), labelStyle);
            createLabelValueRow(sheet, rowNum++, "Total Days Present:", String.valueOf(totalDaysPresent), labelStyle);
            createLabelValueRow(sheet, rowNum++, "Total Absences:", String.valueOf(totalAbsences), labelStyle);

            if (firstDate != null && lastDate != null) {
                createLabelValueRow(sheet, rowNum++, "First Immersion Day:", 
                    firstDate.format(DateTimeFormatter.ofPattern("MMM dd, yyyy")), labelStyle);
                createLabelValueRow(sheet, rowNum++, "Last Immersion Day:", 
                    lastDate.format(DateTimeFormatter.ofPattern("MMM dd, yyyy")), labelStyle);
                createLabelValueRow(sheet, rowNum++, "Total Duration:", 
                    ChronoUnit.DAYS.between(firstDate, lastDate) + 1 + " days", labelStyle);
            }
            rowNum++;

            if (!monthlyHours.isEmpty()) {
                sheet.createRow(rowNum++).createCell(0).setCellValue("MONTHLY BREAKDOWN");
                XSSFRow monthHeaderRow = sheet.createRow(rowNum++);

                Cell monthCell = monthHeaderRow.createCell(0);
                monthCell.setCellValue("Month");
                monthCell.setCellStyle(headerStyle);

                Cell daysCell = monthHeaderRow.createCell(1);
                daysCell.setCellValue("Days Present");
                daysCell.setCellStyle(headerStyle);

                Cell hoursCell = monthHeaderRow.createCell(2);
                hoursCell.setCellValue("Hours Completed");
                hoursCell.setCellStyle(headerStyle);

                for (Map.Entry<String, Double> entry : monthlyHours.entrySet()) {
                    XSSFRow monthRow = sheet.createRow(rowNum++);
                    monthRow.createCell(0).setCellValue(entry.getKey());
                    monthRow.createCell(1).setCellValue(monthlyDays.getOrDefault(entry.getKey(), 0));
                    monthRow.createCell(2).setCellValue(String.format("%.1f hours", entry.getValue()));
                }
                rowNum++;
            }

            sheet.createRow(rowNum++).createCell(0).setCellValue("DETAILED ATTENDANCE RECORDS");
            XSSFRow headerRow = sheet.createRow(rowNum++);
            String[] headers = {"Date", "Day", "Time In", "Time Out", "Work Duration", "Status"};
            for (int i = 0; i < headers.length; i++) {
                Cell cell = headerRow.createCell(i);
                cell.setCellValue(headers[i]);
                cell.setCellStyle(headerStyle);
            }

            rsAttendance.beforeFirst();

            SimpleDateFormat displayFormat = new SimpleDateFormat("MMM dd, yyyy");
            SimpleDateFormat dayFormat = new SimpleDateFormat("EEEE");
            DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("h:mm a");

            while (rsAttendance.next()) {
                XSSFRow dataRow = sheet.createRow(rowNum++);

                String dateStr = rsAttendance.getString("Date");
                String timeIn = rsAttendance.getString("TimeIn");
                String timeOut = rsAttendance.getString("TimeOut");
                String workDuration = rsAttendance.getString("workduration");

                java.sql.Date sqlDate = java.sql.Date.valueOf(dateStr);
                String formattedDate = displayFormat.format(sqlDate);
                String dayOfWeek = dayFormat.format(sqlDate);

                String formattedTimeIn = "";
                String formattedTimeOut = "";
                String status = "Present";

                if (timeIn != null) {
                    LocalDateTime timeInDateTime = LocalDateTime.parse(timeIn, 
                        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                    formattedTimeIn = timeInDateTime.format(timeFormatter);

                    if (timeInDateTime.getHour() >= 9) {
                        status = "Late";
                    }
                }

                if (timeOut != null) {
                    LocalDateTime timeOutDateTime = LocalDateTime.parse(timeOut, 
                        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                    formattedTimeOut = timeOutDateTime.format(timeFormatter);
                } else {
                    formattedTimeOut = "Not recorded";
                }

                dataRow.createCell(0).setCellValue(formattedDate);
                dataRow.createCell(1).setCellValue(dayOfWeek);
                dataRow.createCell(2).setCellValue(formattedTimeIn);
                dataRow.createCell(3).setCellValue(formattedTimeOut);
                dataRow.createCell(4).setCellValue(workDuration != null ? workDuration : "Incomplete");
                dataRow.createCell(5).setCellValue(status);
            }

            for (int i = 0; i < 6; i++) {
                sheet.autoSizeColumn(i);
            }

            try (FileOutputStream fileOut = new FileOutputStream(outputFile)) {
                workbook.write(fileOut);
            }

            workbook.close();
            rsAttendance.close();
            pstAttendance.close();
            rsStudent.close();
            pstStudent.close();
    }
    
    private void createLabelValueRow(XSSFSheet sheet, int rowNum, String label, String value, CellStyle labelStyle) {
        XSSFRow row = sheet.createRow(rowNum);
        Cell labelCell = row.createCell(0);
        labelCell.setCellValue(label);
        labelCell.setCellStyle(labelStyle);
        row.createCell(1).setCellValue(value);
    }
    
    private int countWeekdays(LocalDate start, LocalDate end) {
        int count = 0;
        LocalDate date = start;
        while (date.isBefore(end) || date.equals(end)) {
            if (!(date.getDayOfWeek() == DayOfWeek.SATURDAY || date.getDayOfWeek() == DayOfWeek.SUNDAY)) {
                count++;
            }
            date = date.plusDays(1);
        }
        return count;
    }
    
}